#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMDB")]
	public partial class clearDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSCarInfo(SCarInfo instance);
    partial void UpdateSCarInfo(SCarInfo instance);
    partial void DeleteSCarInfo(SCarInfo instance);
    #endregion
		
		public clearDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clearDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clearDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clearDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clearDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SCarInfo> SCarInfo
		{
			get
			{
				return this.GetTable<SCarInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SCarInfo")]
	public partial class SCarInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sciID;
		
		private int _scID;
		
		private int _gdID;
		
		private int _scNum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsciIDChanging(int value);
    partial void OnsciIDChanged();
    partial void OnscIDChanging(int value);
    partial void OnscIDChanged();
    partial void OngdIDChanging(int value);
    partial void OngdIDChanged();
    partial void OnscNumChanging(int value);
    partial void OnscNumChanged();
    #endregion
		
		public SCarInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sciID
		{
			get
			{
				return this._sciID;
			}
			set
			{
				if ((this._sciID != value))
				{
					this.OnsciIDChanging(value);
					this.SendPropertyChanging();
					this._sciID = value;
					this.SendPropertyChanged("sciID");
					this.OnsciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scID", DbType="Int NOT NULL")]
		public int scID
		{
			get
			{
				return this._scID;
			}
			set
			{
				if ((this._scID != value))
				{
					this.OnscIDChanging(value);
					this.SendPropertyChanging();
					this._scID = value;
					this.SendPropertyChanged("scID");
					this.OnscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdID", DbType="Int NOT NULL")]
		public int gdID
		{
			get
			{
				return this._gdID;
			}
			set
			{
				if ((this._gdID != value))
				{
					this.OngdIDChanging(value);
					this.SendPropertyChanging();
					this._gdID = value;
					this.SendPropertyChanged("gdID");
					this.OngdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scNum", DbType="Int NOT NULL")]
		public int scNum
		{
			get
			{
				return this._scNum;
			}
			set
			{
				if ((this._scNum != value))
				{
					this.OnscNumChanging(value);
					this.SendPropertyChanging();
					this._scNum = value;
					this.SendPropertyChanged("scNum");
					this.OnscNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
