#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMDB")]
	public partial class pingjiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertGoodEvaluate(GoodEvaluate instance);
    partial void UpdateGoodEvaluate(GoodEvaluate instance);
    partial void DeleteGoodEvaluate(GoodEvaluate instance);
    #endregion
		
		public pingjiaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pingjiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pingjiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pingjiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pingjiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GoodEvaluate> GoodEvaluate
		{
			get
			{
				return this.GetTable<GoodEvaluate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoodEvaluate")]
	public partial class GoodEvaluate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _geID;
		
		private int _uID;
		
		private int _gdID;
		
		private string _geContent;
		
		private System.DateTime _geAddTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngeIDChanging(int value);
    partial void OngeIDChanged();
    partial void OnuIDChanging(int value);
    partial void OnuIDChanged();
    partial void OngdIDChanging(int value);
    partial void OngdIDChanged();
    partial void OngeContentChanging(string value);
    partial void OngeContentChanged();
    partial void OngeAddTimeChanging(System.DateTime value);
    partial void OngeAddTimeChanged();
    #endregion
		
		public GoodEvaluate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int geID
		{
			get
			{
				return this._geID;
			}
			set
			{
				if ((this._geID != value))
				{
					this.OngeIDChanging(value);
					this.SendPropertyChanging();
					this._geID = value;
					this.SendPropertyChanged("geID");
					this.OngeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uID", DbType="Int NOT NULL")]
		public int uID
		{
			get
			{
				return this._uID;
			}
			set
			{
				if ((this._uID != value))
				{
					this.OnuIDChanging(value);
					this.SendPropertyChanging();
					this._uID = value;
					this.SendPropertyChanged("uID");
					this.OnuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdID", DbType="Int NOT NULL")]
		public int gdID
		{
			get
			{
				return this._gdID;
			}
			set
			{
				if ((this._gdID != value))
				{
					this.OngdIDChanging(value);
					this.SendPropertyChanging();
					this._gdID = value;
					this.SendPropertyChanged("gdID");
					this.OngdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geContent", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string geContent
		{
			get
			{
				return this._geContent;
			}
			set
			{
				if ((this._geContent != value))
				{
					this.OngeContentChanging(value);
					this.SendPropertyChanging();
					this._geContent = value;
					this.SendPropertyChanged("geContent");
					this.OngeContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geAddTime", DbType="DateTime NOT NULL")]
		public System.DateTime geAddTime
		{
			get
			{
				return this._geAddTime;
			}
			set
			{
				if ((this._geAddTime != value))
				{
					this.OngeAddTimeChanging(value);
					this.SendPropertyChanging();
					this._geAddTime = value;
					this.SendPropertyChanged("geAddTime");
					this.OngeAddTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
