<?xml version="1.0" encoding="utf-8"?><Database Name="SMDB" Class="pingjiaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\SMDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GoodEvaluate" Member="GoodEvaluate">
    <Type Name="GoodEvaluate">
      <Column Name="geID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gdID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="geContent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="geAddTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>